# This is the Sprntr build and deployment workflow.

name: Build + Deploy

on:
  push:
    branches: [ release ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Install dependencies
        run: yarn install

      - name: Run unit tests
        run: yarn test:unit

      - name: Run e2e tests
        uses: cypress-io/github-action@v1
        with:
          command: yarn test:e2e --headless

      - name: Build site
        run: yarn build
  
      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: dist