# This is the Sprntr build and deployment workflow.

name: Build + Deploy

on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Install dependencies
        run: yarn install

      - name: Run Tests
        run: yarn test

      - name: Build site
        run: yarn build
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy site
        run: yarn deploy:ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
